### ISSUE TITLE
Run with privileges ?

### ISSUE THREAD

**Issue by little-kawa** [morRubin/NegoExRelay#1]
Hello,

Thank you for this tool.
Do we need to run it with privileges (for the SMB server port opening) ?
If I change the port to avoid to run it with privilege, can we still trigger a relay ?

**Comment by morRubin** [comment]
Yes. By default ports under 1024 require privileges.
If you want to open SMB server on port 445 you will have to use admin rights. Also note that if you run it in Windows machine, port 445 is used by Windows default SMB server, so you will have to disable the service before trying to use this port.

You can change the port to run the SMB server and still trigger relay. **But** you the client tries to authenticate to you will have to use the port you have used for the SMB server (For example if you used port 5555 for SMB server, the client will have to use SMB over port 5555 to authenticate to the attacker machine which will later relay it to the victim with normal SMB port).
